apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp
spec:
  type: ClusterIP
  ports:
    - name: 80-80
      port: 80
      targetPort: 80
  selector:
    app: myapp
    type: front-end